### ISSUE TITLE
[h1, h2] title no underline (style.css)

### ISSUE THREAD

**Issue by samwhelp** [GitbookIO/plugin-fontsettings#2]
gitbook new version 

[h1, h2] title no underline (style.css)

I use this fix(refer old version).

``` css
.book .book-body .page-wrapper .page-inner section.normal h1 {
    border-bottom: 1px solid #eee;
}

.book .book-body .page-wrapper .page-inner section.normal h2 {
    border-bottom: 1px solid #eee;
}
```

[Extend website and ebook style](http://help.gitbook.com/styling/book.html)
